Optional and empty services
AtlasOfLivingAustralia/dashboard pull request #103
Opened 2020-12-17 21:32 UTC by vjrj

Currently the dashboard only works when all queries returns values and all the ALA services are working as expected. This PR:
- Addresses partially #96 making some services optional 
- It also addresses partially #85. This is also interesting in the LA community as it will allow to run the LA dashboard in new LA portals without data or LA portals without some services (like BIE, or spatial).

I've tested with:
- ALA services (double checking that I don't break nothing with this PR in the ALA production dashboard, attached my properties).
- An empty LA new deployment
- And now that I can generate inventories and `/data` directories easily, I also tested with Canadensys, Sweden and Vermont portals.

[ALA-dashboard-config.properties.txt](https://github.com/AtlasOfLivingAustralia/dashboard/files/5712261/dashboard-config.properties.txt)

2021-01-20 03:36 UTC, ansell requested changes
Bumping the ala-bootstrap3 plugin version is the main change I can see.

2021-01-20 03:36 UTC, ansell commented on build.gradle
> +    compile "org.grails.plugins:ala-bootstrap3:3.2.0"
This needs to be bumped to 3.2.3 to pickup an important fix.

2021-01-20 03:36 UTC, ansell commented on grails-app/conf/application.yml
> +useCitizenScienceService: true
Feel free to default these to `false` either here or in Ansible, and ALA, as the main user, can switch them back on using ansible when deploying our dashboard instance.

2021-01-20 07:36 UTC, vjrj commented
Tested locally again with ALA services, and works well to me.

![2021-08-20-08-25-21-screenshot](https://user-images.githubusercontent.com/180085/105142146-81be7a80-5afa-11eb-90cd-6e7e576b4fd3.png)

2021-01-26 13:44 UTC, vjrj commented
@nickdos or @djtfmartin Can you have a look of this PR? I've tested a lot with different portals.
There are people in the community waiting for this. Thanks!

Related: https://atlaslivingaustralia.slack.com/archives/CCTFGEU1G/p1608241694318900

2021-01-26 13:48 UTC, djtfmartin approved these changes
LGTM

2021-01-26 13:48 UTC, merged

2021-01-26 13:55 UTC, vjrj commented
Thanks @djtfmartin!

It's possible to build this version as a snapshot in nexus?
https://nexus.ala.org.au/#nexus-search;classname~dashboard
https://github.com/AtlasOfLivingAustralia/dashboard/blob/master/build.gradle#L18

Thanks again!

2021-01-26 13:57 UTC, vjrj commented
Ok, a new build of the dashboard is now nexus. Great, we'll use in short...